version: '3'
services:
  flutter_db:
    build: ./contents/mysql
    container_name: base_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: flutter2812
      MYSQL_DATABASE: flutter
      MYSQL_USER: flutter
      MYSQL_PASSWORD: flutter2812
      TZ: 'Asia/Tokyo'
    command: --innodb-use-native-aio=0
    volumes:
      - ./cache/db/ :/var/lib/mysql
      - ./contents/mysql/conf.d :/etc/mysql/conf.d/
      - ./log/mysql :/var/log/mysql
    ports:
      - 33306:3306

  flutter_demo_web:
    build: ../flutter_app_web
    container_name: flutter_demo_web
    restart: always
    env_file: ./contents/web/docker.env
    ports:
      - "8000:8000"
    command: sh -c "sleep 5; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "../flutter_app_web :/app/web/current"
    depends_on:
      - flutter_db
    tty: true
